version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: wof-sync-os-postcodes
    binary: wof-sync-os-postcodes
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    main: ./cmd/wof-sync-os-postcodes
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
